FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && python -m playwright install --with-deps chromium

COPY app/ ./app/
COPY run.py .

EXPOSE 5000

CMD ["python", "run.py"]
